### ISSUE TITLE
error at cudaSuccess?

### ISSUE THREAD

**Issue by JanceeLee** [HyeonwooNoh/DeconvNet#1]
Hi,

I'm trying to train DeconvNet and run 001_start_train.sh ,but  the error is:

F0907 11:37:08.948395  5462 syncedmem.cpp:51] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
**\* Check failure stack trace: ***
    @     0x7fe9bc71da3d  google::LogMessage::Fail()
    @     0x7fe9bc721ed7  google::LogMessage::SendToLog()
    @     0x7fe9bc71fd39  google::LogMessage::Flush()
    @     0x7fe9bc72003d  google::LogMessageFatal::~LogMessageFatal()
    @           0x6a6f8e  caffe::SyncedMemory::to_gpu()
    @           0x6a6b20  caffe::SyncedMemory::mutable_gpu_data()
    @           0x6aacfd  caffe::Blob<>::mutable_gpu_data()
    @           0x6d8b7d  caffe::UnpoolingLayer<>::Forward_gpu()
    @           0x577814  caffe::Layer<>::Forward()
    @           0x58e419  caffe::Net<>::ForwardFromTo()
    @           0x58e171  caffe::Net<>::ForwardPrefilled()
    @           0x58e5a4  caffe::Net<>::Forward()
    @           0x6b3962  caffe::Solver<>::Test()
    @           0x6b376d  caffe::Solver<>::TestAll()
    @           0x6b2b51  caffe::Solver<>::Step()
    @           0x6b268b  caffe::Solver<>::Solve()
    @           0x5738c1  train()
    @           0x575903  main
    @       0x36e9a1ed5d  (unknown)
    @           0x572df9  (unknown)
./start_train.sh: line 6:  5462 Aborted                 GLOG_log_dir=$LOGDIR $CAFFE train -solver $SOLVER -weights $WEIGHTS -gpu 0
cp: cannot stat `./snapshot/stage_1_train_iter_20000.caffemodel': No such file or directory

I'm a new newbie in caffe , can u help me? thinks.

**Comment by HyeonwooNoh** [comment]
I guess you have insufficient memory space in your GPU. I successfully trained DeconvNet on NVIDIA titan X with more than 12 GB memory and it would be hard to train DeconvNet on other gpu due to the lack of memory space.

**Comment by JanceeLee** [comment]
Ok, thanks for your answer , I try to think other ways.
