### ISSUE TITLE
Data URL is down

### ISSUE THREAD

**Issue by tiagojdias** [HyeonwooNoh/DeconvNet#9]
I'm not being able to dowload the data.
Is it something from me? I even checked and the url provided is down.

Can the data be provided by other way?

**Comment by HyeonwooNoh** [comment]
That's becuase the data sever is down untill 12/25 as the server room is
under construction. We couldn't provide the data until 12/25 as we don't
have the data locally. Could you try after 12/25?

2016년 12월 18일 (일) 오후 2:56, Tiago J. Dias <notifications@github.com>님이 작성:

**Comment by tiagojdias** [comment]
Thanks for the fast reply.

I'll wait unitl 25th.
